# Generated by Django 3.0 on 2019-12-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postt',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default=0, max_length=120, upload_to=''),
            preserve_default=False,
        ),
    ]
